name: continuous integration php
on: 
  push:
    branches: [develop]
    branches: [main]
  pull_request:
    branches: [develop]
    branches: [main]
jobs: 
  ci_to_master:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          php_version: '8.0'
      - name: 'Install Dependencies'
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: 'Execute tests (Unit) via phpcs' 
        run: composer phpcs-auto-check-project
      - name: 'Execute tests (Unit) via PHPUnit' 
        run: composer phpunit





